/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppResumesRouteImport } from './routes/app.resumes'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppResumesIndexRouteImport } from './routes/app.resumes.index'
import { Route as AppResumesResumeIdEditRouteImport } from './routes/app.resumes.$resumeId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppResumesRoute = AppResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppResumesIndexRoute = AppResumesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppResumesRoute,
} as any)
const AppResumesResumeIdEditRoute = AppResumesResumeIdEditRouteImport.update({
  id: '/$resumeId/edit',
  path: '/$resumeId/edit',
  getParentRoute: () => AppResumesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/app/resumes': typeof AppResumesRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/resumes/': typeof AppResumesIndexRoute
  '/app/resumes/$resumeId/edit': typeof AppResumesResumeIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/app/settings': typeof AppSettingsRoute
  '/app': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/resumes': typeof AppResumesIndexRoute
  '/app/resumes/$resumeId/edit': typeof AppResumesResumeIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/app/resumes': typeof AppResumesRouteWithChildren
  '/app/settings': typeof AppSettingsRoute
  '/app/': typeof AppIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/resumes/': typeof AppResumesIndexRoute
  '/app/resumes/$resumeId/edit': typeof AppResumesResumeIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/sign-in'
    | '/sign-up'
    | '/app/resumes'
    | '/app/settings'
    | '/app/'
    | '/api/auth/$'
    | '/app/resumes/'
    | '/app/resumes/$resumeId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/sign-up'
    | '/app/settings'
    | '/app'
    | '/api/auth/$'
    | '/app/resumes'
    | '/app/resumes/$resumeId/edit'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/sign-in'
    | '/sign-up'
    | '/app/resumes'
    | '/app/settings'
    | '/app/'
    | '/api/auth/$'
    | '/app/resumes/'
    | '/app/resumes/$resumeId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/resumes': {
      id: '/app/resumes'
      path: '/resumes'
      fullPath: '/app/resumes'
      preLoaderRoute: typeof AppResumesRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/resumes/': {
      id: '/app/resumes/'
      path: '/'
      fullPath: '/app/resumes/'
      preLoaderRoute: typeof AppResumesIndexRouteImport
      parentRoute: typeof AppResumesRoute
    }
    '/app/resumes/$resumeId/edit': {
      id: '/app/resumes/$resumeId/edit'
      path: '/$resumeId/edit'
      fullPath: '/app/resumes/$resumeId/edit'
      preLoaderRoute: typeof AppResumesResumeIdEditRouteImport
      parentRoute: typeof AppResumesRoute
    }
  }
}

interface AppResumesRouteChildren {
  AppResumesIndexRoute: typeof AppResumesIndexRoute
  AppResumesResumeIdEditRoute: typeof AppResumesResumeIdEditRoute
}

const AppResumesRouteChildren: AppResumesRouteChildren = {
  AppResumesIndexRoute: AppResumesIndexRoute,
  AppResumesResumeIdEditRoute: AppResumesResumeIdEditRoute,
}

const AppResumesRouteWithChildren = AppResumesRoute._addFileChildren(
  AppResumesRouteChildren,
)

interface AppRouteChildren {
  AppResumesRoute: typeof AppResumesRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppResumesRoute: AppResumesRouteWithChildren,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
